{"ip_str": "0.0.0.0", "errors": {"get_ip_error": "HTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /get (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e436eb610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}}