{"ip_str": "104.238.182.217", "errors": {"VPN_error": "Timeout exceeded.\n<pexpect.pty_spawn.spawn object at 0x7fd169c8d2e0>\ncommand: /usr/sbin/openvpn\nargs: ['/usr/sbin/openvpn', '/home/NetPlatform/configurations/us9617.nordvpn.com.udp.ovpn']\nbuffer (last 100 chars): b'UDP link local: (not bound)\\r\\nWed Oct 26 21:18:55 2022 UDP link remote: [AF_INET]45.38.182.114:1194\\r\\n'\nbefore (last 100 chars): b'UDP link local: (not bound)\\r\\nWed Oct 26 21:18:55 2022 UDP link remote: [AF_INET]45.38.182.114:1194\\r\\n'\nafter: <class 'pexpect.exceptions.TIMEOUT'>\nmatch: None\nmatch_index: None\nexitstatus: None\nflag_eof: False\npid: 8\nchild_fd: 5\nclosed: False\ntimeout: 30\ndelimiter: <class 'pexpect.exceptions.EOF'>\nlogfile: None\nlogfile_read: None\nlogfile_send: None\nmaxread: 2000\nignorecase: False\nsearchwindowsize: None\ndelaybeforesend: 0.05\ndelayafterclose: 0.1\ndelayafterterminate: 0.1\nsearcher: searcher_re:\n    0: re.compile(b'Initialization Sequence Completed')"}}